/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureOpenAI.Client.OpenAPIDateConverter;

namespace AzureOpenAI.Model
{
    /// <summary>
    /// CreateChatCompletionRequestAllOfFunctionCallOneOf
    /// </summary>
    [DataContract(Name = "createChatCompletionRequest_allOf_function_call_oneOf")]
    public partial class CreateChatCompletionRequestAllOfFunctionCallOneOf : IEquatable<CreateChatCompletionRequestAllOfFunctionCallOneOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateChatCompletionRequestAllOfFunctionCallOneOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateChatCompletionRequestAllOfFunctionCallOneOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateChatCompletionRequestAllOfFunctionCallOneOf" /> class.
        /// </summary>
        /// <param name="name">The name of the function to call. (required).</param>
        public CreateChatCompletionRequestAllOfFunctionCallOneOf(string name = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateChatCompletionRequestAllOfFunctionCallOneOf and cannot be null");
            }
            this.Name = name;
        }

        /// <summary>
        /// The name of the function to call.
        /// </summary>
        /// <value>The name of the function to call.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateChatCompletionRequestAllOfFunctionCallOneOf {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateChatCompletionRequestAllOfFunctionCallOneOf);
        }

        /// <summary>
        /// Returns true if CreateChatCompletionRequestAllOfFunctionCallOneOf instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateChatCompletionRequestAllOfFunctionCallOneOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateChatCompletionRequestAllOfFunctionCallOneOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
