/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureOpenAI.Client.OpenAPIDateConverter;

namespace AzureOpenAI.Model
{
    /// <summary>
    /// EmbeddingsCreate200ResponseDataInner
    /// </summary>
    [DataContract(Name = "embeddings_create_200_response_data_inner")]
    public partial class EmbeddingsCreate200ResponseDataInner : IEquatable<EmbeddingsCreate200ResponseDataInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddingsCreate200ResponseDataInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmbeddingsCreate200ResponseDataInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddingsCreate200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="index">index (required).</param>
        /// <param name="varObject">varObject (required).</param>
        /// <param name="embedding">embedding (required).</param>
        public EmbeddingsCreate200ResponseDataInner(int index = default(int), string varObject = default(string), List<decimal> embedding = default(List<decimal>))
        {
            this.Index = index;
            // to ensure "varObject" is required (not null)
            if (varObject == null)
            {
                throw new ArgumentNullException("varObject is a required property for EmbeddingsCreate200ResponseDataInner and cannot be null");
            }
            this.VarObject = varObject;
            // to ensure "embedding" is required (not null)
            if (embedding == null)
            {
                throw new ArgumentNullException("embedding is a required property for EmbeddingsCreate200ResponseDataInner and cannot be null");
            }
            this.Embedding = embedding;
        }

        /// <summary>
        /// Gets or Sets Index
        /// </summary>
        [DataMember(Name = "index", IsRequired = true, EmitDefaultValue = true)]
        public int Index { get; set; }

        /// <summary>
        /// Gets or Sets VarObject
        /// </summary>
        [DataMember(Name = "object", IsRequired = true, EmitDefaultValue = true)]
        public string VarObject { get; set; }

        /// <summary>
        /// Gets or Sets Embedding
        /// </summary>
        [DataMember(Name = "embedding", IsRequired = true, EmitDefaultValue = true)]
        public List<decimal> Embedding { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmbeddingsCreate200ResponseDataInner {\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  VarObject: ").Append(VarObject).Append("\n");
            sb.Append("  Embedding: ").Append(Embedding).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmbeddingsCreate200ResponseDataInner);
        }

        /// <summary>
        /// Returns true if EmbeddingsCreate200ResponseDataInner instances are equal
        /// </summary>
        /// <param name="input">Instance of EmbeddingsCreate200ResponseDataInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmbeddingsCreate200ResponseDataInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Index == input.Index ||
                    this.Index.Equals(input.Index)
                ) && 
                (
                    this.VarObject == input.VarObject ||
                    (this.VarObject != null &&
                    this.VarObject.Equals(input.VarObject))
                ) && 
                (
                    this.Embedding == input.Embedding ||
                    this.Embedding != null &&
                    input.Embedding != null &&
                    this.Embedding.SequenceEqual(input.Embedding)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Index.GetHashCode();
                if (this.VarObject != null)
                {
                    hashCode = (hashCode * 59) + this.VarObject.GetHashCode();
                }
                if (this.Embedding != null)
                {
                    hashCode = (hashCode * 59) + this.Embedding.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
