/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureOpenAI.Client.OpenAPIDateConverter;

namespace AzureOpenAI.Model
{
    /// <summary>
    /// Error codes for the inner error object.
    /// </summary>
    /// <value>Error codes for the inner error object.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum InnerErrorCode
    {
        /// <summary>
        /// Enum ResponsibleAIPolicyViolation for value: ResponsibleAIPolicyViolation
        /// </summary>
        [EnumMember(Value = "ResponsibleAIPolicyViolation")]
        ResponsibleAIPolicyViolation = 1
    }

}
