/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureOpenAI.Client.OpenAPIDateConverter;

namespace AzureOpenAI.Model
{
    /// <summary>
    /// Content filtering results for a single prompt in the request.
    /// </summary>
    [DataContract(Name = "promptFilterResult")]
    public partial class PromptFilterResult : IEquatable<PromptFilterResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PromptFilterResult" /> class.
        /// </summary>
        /// <param name="promptIndex">promptIndex.</param>
        /// <param name="contentFilterResults">contentFilterResults.</param>
        public PromptFilterResult(int promptIndex = default(int), ContentFilterResults contentFilterResults = default(ContentFilterResults))
        {
            this.PromptIndex = promptIndex;
            this.ContentFilterResults = contentFilterResults;
        }

        /// <summary>
        /// Gets or Sets PromptIndex
        /// </summary>
        [DataMember(Name = "prompt_index", EmitDefaultValue = true)]
        public int PromptIndex { get; set; }

        /// <summary>
        /// Gets or Sets ContentFilterResults
        /// </summary>
        [DataMember(Name = "content_filter_results", EmitDefaultValue = true)]
        public ContentFilterResults ContentFilterResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PromptFilterResult {\n");
            sb.Append("  PromptIndex: ").Append(PromptIndex).Append("\n");
            sb.Append("  ContentFilterResults: ").Append(ContentFilterResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PromptFilterResult);
        }

        /// <summary>
        /// Returns true if PromptFilterResult instances are equal
        /// </summary>
        /// <param name="input">Instance of PromptFilterResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PromptFilterResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PromptIndex == input.PromptIndex ||
                    this.PromptIndex.Equals(input.PromptIndex)
                ) && 
                (
                    this.ContentFilterResults == input.ContentFilterResults ||
                    (this.ContentFilterResults != null &&
                    this.ContentFilterResults.Equals(input.ContentFilterResults))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.PromptIndex.GetHashCode();
                if (this.ContentFilterResults != null)
                {
                    hashCode = (hashCode * 59) + this.ContentFilterResults.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
