/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureOpenAI.Client.OpenAPIDateConverter;

namespace AzureOpenAI.Model
{
    /// <summary>
    /// Defines the format of the output.
    /// </summary>
    /// <value>Defines the format of the output.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ResponseFormat
    {
        /// <summary>
        /// Enum Json for value: json
        /// </summary>
        [EnumMember(Value = "json")]
        Json = 1,

        /// <summary>
        /// Enum Text for value: text
        /// </summary>
        [EnumMember(Value = "text")]
        Text = 2,

        /// <summary>
        /// Enum Srt for value: srt
        /// </summary>
        [EnumMember(Value = "srt")]
        Srt = 3,

        /// <summary>
        /// Enum VerboseJson for value: verbose_json
        /// </summary>
        [EnumMember(Value = "verbose_json")]
        VerboseJson = 4,

        /// <summary>
        /// Enum Vtt for value: vtt
        /// </summary>
        [EnumMember(Value = "vtt")]
        Vtt = 5
    }

}
