/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureOpenAI.Client.OpenAPIDateConverter;
using System.Reflection;

namespace AzureOpenAI.Model
{
    /// <summary>
    /// TranscriptionsCreate200Response
    /// </summary>
    [JsonConverter(typeof(TranscriptionsCreate200ResponseJsonConverter))]
    [DataContract(Name = "Transcriptions_Create_200_response")]
    public partial class TranscriptionsCreate200Response : AbstractOpenAPISchema, IEquatable<TranscriptionsCreate200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranscriptionsCreate200Response" /> class
        /// with the <see cref="AudioResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AudioResponse.</param>
        public TranscriptionsCreate200Response(AudioResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranscriptionsCreate200Response" /> class
        /// with the <see cref="AudioVerboseResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AudioVerboseResponse.</param>
        public TranscriptionsCreate200Response(AudioVerboseResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(AudioResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(AudioVerboseResponse))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: AudioResponse, AudioVerboseResponse");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `AudioResponse`. If the actual instance is not `AudioResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AudioResponse</returns>
        public AudioResponse GetAudioResponse()
        {
            return (AudioResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `AudioVerboseResponse`. If the actual instance is not `AudioVerboseResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AudioVerboseResponse</returns>
        public AudioVerboseResponse GetAudioVerboseResponse()
        {
            return (AudioVerboseResponse)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TranscriptionsCreate200Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, TranscriptionsCreate200Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of TranscriptionsCreate200Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of TranscriptionsCreate200Response</returns>
        public static TranscriptionsCreate200Response FromJson(string jsonString)
        {
            TranscriptionsCreate200Response newTranscriptionsCreate200Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newTranscriptionsCreate200Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(AudioResponse).GetProperty("AdditionalProperties") == null)
                {
                    newTranscriptionsCreate200Response = new TranscriptionsCreate200Response(JsonConvert.DeserializeObject<AudioResponse>(jsonString, TranscriptionsCreate200Response.SerializerSettings));
                }
                else
                {
                    newTranscriptionsCreate200Response = new TranscriptionsCreate200Response(JsonConvert.DeserializeObject<AudioResponse>(jsonString, TranscriptionsCreate200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("AudioResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AudioResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(AudioVerboseResponse).GetProperty("AdditionalProperties") == null)
                {
                    newTranscriptionsCreate200Response = new TranscriptionsCreate200Response(JsonConvert.DeserializeObject<AudioVerboseResponse>(jsonString, TranscriptionsCreate200Response.SerializerSettings));
                }
                else
                {
                    newTranscriptionsCreate200Response = new TranscriptionsCreate200Response(JsonConvert.DeserializeObject<AudioVerboseResponse>(jsonString, TranscriptionsCreate200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("AudioVerboseResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AudioVerboseResponse: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newTranscriptionsCreate200Response;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TranscriptionsCreate200Response);
        }

        /// <summary>
        /// Returns true if TranscriptionsCreate200Response instances are equal
        /// </summary>
        /// <param name="input">Instance of TranscriptionsCreate200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TranscriptionsCreate200Response input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for TranscriptionsCreate200Response
    /// </summary>
    public class TranscriptionsCreate200ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(TranscriptionsCreate200Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return TranscriptionsCreate200Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
