/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing AudioResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AudioResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AudioResponse
        //private AudioResponse instance;

        public AudioResponseTests()
        {
            // TODO uncomment below to create an instance of AudioResponse
            //instance = new AudioResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AudioResponse
        /// </summary>
        [Fact]
        public void AudioResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AudioResponse
            //Assert.IsType<AudioResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
    }
}
