/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing AudioSegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AudioSegmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AudioSegment
        //private AudioSegment instance;

        public AudioSegmentTests()
        {
            // TODO uncomment below to create an instance of AudioSegment
            //instance = new AudioSegment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AudioSegment
        /// </summary>
        [Fact]
        public void AudioSegmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" AudioSegment
            //Assert.IsType<AudioSegment>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Seek'
        /// </summary>
        [Fact]
        public void SeekTest()
        {
            // TODO unit test for the property 'Seek'
        }

        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }

        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'AvgLogprob'
        /// </summary>
        [Fact]
        public void AvgLogprobTest()
        {
            // TODO unit test for the property 'AvgLogprob'
        }

        /// <summary>
        /// Test the property 'CompressionRatio'
        /// </summary>
        [Fact]
        public void CompressionRatioTest()
        {
            // TODO unit test for the property 'CompressionRatio'
        }

        /// <summary>
        /// Test the property 'NoSpeechProb'
        /// </summary>
        [Fact]
        public void NoSpeechProbTest()
        {
            // TODO unit test for the property 'NoSpeechProb'
        }
    }
}
