/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing ChatCompletionResponseMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatCompletionResponseMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatCompletionResponseMessage
        //private ChatCompletionResponseMessage instance;

        public ChatCompletionResponseMessageTests()
        {
            // TODO uncomment below to create an instance of ChatCompletionResponseMessage
            //instance = new ChatCompletionResponseMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatCompletionResponseMessage
        /// </summary>
        [Fact]
        public void ChatCompletionResponseMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatCompletionResponseMessage
            //Assert.IsType<ChatCompletionResponseMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'FunctionCall'
        /// </summary>
        [Fact]
        public void FunctionCallTest()
        {
            // TODO unit test for the property 'FunctionCall'
        }
    }
}
