/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing ChatCompletionChoiceCommon
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatCompletionChoiceCommonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatCompletionChoiceCommon
        //private ChatCompletionChoiceCommon instance;

        public ChatCompletionChoiceCommonTests()
        {
            // TODO uncomment below to create an instance of ChatCompletionChoiceCommon
            //instance = new ChatCompletionChoiceCommon();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatCompletionChoiceCommon
        /// </summary>
        [Fact]
        public void ChatCompletionChoiceCommonInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatCompletionChoiceCommon
            //Assert.IsType<ChatCompletionChoiceCommon>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'FinishReason'
        /// </summary>
        [Fact]
        public void FinishReasonTest()
        {
            // TODO unit test for the property 'FinishReason'
        }
    }
}
