/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing ChatCompletionRequestMessageFunctionCall
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatCompletionRequestMessageFunctionCallTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatCompletionRequestMessageFunctionCall
        //private ChatCompletionRequestMessageFunctionCall instance;

        public ChatCompletionRequestMessageFunctionCallTests()
        {
            // TODO uncomment below to create an instance of ChatCompletionRequestMessageFunctionCall
            //instance = new ChatCompletionRequestMessageFunctionCall();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatCompletionRequestMessageFunctionCall
        /// </summary>
        [Fact]
        public void ChatCompletionRequestMessageFunctionCallInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatCompletionRequestMessageFunctionCall
            //Assert.IsType<ChatCompletionRequestMessageFunctionCall>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Fact]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }
    }
}
