/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing CompletionsCreate200ResponseChoicesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompletionsCreate200ResponseChoicesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompletionsCreate200ResponseChoicesInner
        //private CompletionsCreate200ResponseChoicesInner instance;

        public CompletionsCreate200ResponseChoicesInnerTests()
        {
            // TODO uncomment below to create an instance of CompletionsCreate200ResponseChoicesInner
            //instance = new CompletionsCreate200ResponseChoicesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompletionsCreate200ResponseChoicesInner
        /// </summary>
        [Fact]
        public void CompletionsCreate200ResponseChoicesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompletionsCreate200ResponseChoicesInner
            //Assert.IsType<CompletionsCreate200ResponseChoicesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Logprobs'
        /// </summary>
        [Fact]
        public void LogprobsTest()
        {
            // TODO unit test for the property 'Logprobs'
        }

        /// <summary>
        /// Test the property 'FinishReason'
        /// </summary>
        [Fact]
        public void FinishReasonTest()
        {
            // TODO unit test for the property 'FinishReason'
        }

        /// <summary>
        /// Test the property 'ContentFilterResults'
        /// </summary>
        [Fact]
        public void ContentFilterResultsTest()
        {
            // TODO unit test for the property 'ContentFilterResults'
        }
    }
}
