/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing CompletionsCreate200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompletionsCreate200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompletionsCreate200Response
        //private CompletionsCreate200Response instance;

        public CompletionsCreate200ResponseTests()
        {
            // TODO uncomment below to create an instance of CompletionsCreate200Response
            //instance = new CompletionsCreate200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompletionsCreate200Response
        /// </summary>
        [Fact]
        public void CompletionsCreate200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompletionsCreate200Response
            //Assert.IsType<CompletionsCreate200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'VarObject'
        /// </summary>
        [Fact]
        public void VarObjectTest()
        {
            // TODO unit test for the property 'VarObject'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'PromptFilterResults'
        /// </summary>
        [Fact]
        public void PromptFilterResultsTest()
        {
            // TODO unit test for the property 'PromptFilterResults'
        }

        /// <summary>
        /// Test the property 'Choices'
        /// </summary>
        [Fact]
        public void ChoicesTest()
        {
            // TODO unit test for the property 'Choices'
        }

        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }
    }
}
