/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing CompletionsCreateRequestStop
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompletionsCreateRequestStopTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompletionsCreateRequestStop
        //private CompletionsCreateRequestStop instance;

        public CompletionsCreateRequestStopTests()
        {
            // TODO uncomment below to create an instance of CompletionsCreateRequestStop
            //instance = new CompletionsCreateRequestStop();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompletionsCreateRequestStop
        /// </summary>
        [Fact]
        public void CompletionsCreateRequestStopInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompletionsCreateRequestStop
            //Assert.IsType<CompletionsCreateRequestStop>(instance);
        }
    }
}
