/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing CompletionsCreate200ResponseUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompletionsCreate200ResponseUsageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompletionsCreate200ResponseUsage
        //private CompletionsCreate200ResponseUsage instance;

        public CompletionsCreate200ResponseUsageTests()
        {
            // TODO uncomment below to create an instance of CompletionsCreate200ResponseUsage
            //instance = new CompletionsCreate200ResponseUsage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompletionsCreate200ResponseUsage
        /// </summary>
        [Fact]
        public void CompletionsCreate200ResponseUsageInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompletionsCreate200ResponseUsage
            //Assert.IsType<CompletionsCreate200ResponseUsage>(instance);
        }

        /// <summary>
        /// Test the property 'CompletionTokens'
        /// </summary>
        [Fact]
        public void CompletionTokensTest()
        {
            // TODO unit test for the property 'CompletionTokens'
        }

        /// <summary>
        /// Test the property 'PromptTokens'
        /// </summary>
        [Fact]
        public void PromptTokensTest()
        {
            // TODO unit test for the property 'PromptTokens'
        }

        /// <summary>
        /// Test the property 'TotalTokens'
        /// </summary>
        [Fact]
        public void TotalTokensTest()
        {
            // TODO unit test for the property 'TotalTokens'
        }
    }
}
