/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing CompletionsCreate200ResponseChoicesInnerLogprobs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompletionsCreate200ResponseChoicesInnerLogprobsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompletionsCreate200ResponseChoicesInnerLogprobs
        //private CompletionsCreate200ResponseChoicesInnerLogprobs instance;

        public CompletionsCreate200ResponseChoicesInnerLogprobsTests()
        {
            // TODO uncomment below to create an instance of CompletionsCreate200ResponseChoicesInnerLogprobs
            //instance = new CompletionsCreate200ResponseChoicesInnerLogprobs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompletionsCreate200ResponseChoicesInnerLogprobs
        /// </summary>
        [Fact]
        public void CompletionsCreate200ResponseChoicesInnerLogprobsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompletionsCreate200ResponseChoicesInnerLogprobs
            //Assert.IsType<CompletionsCreate200ResponseChoicesInnerLogprobs>(instance);
        }

        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }

        /// <summary>
        /// Test the property 'TokenLogprobs'
        /// </summary>
        [Fact]
        public void TokenLogprobsTest()
        {
            // TODO unit test for the property 'TokenLogprobs'
        }

        /// <summary>
        /// Test the property 'TopLogprobs'
        /// </summary>
        [Fact]
        public void TopLogprobsTest()
        {
            // TODO unit test for the property 'TopLogprobs'
        }

        /// <summary>
        /// Test the property 'TextOffset'
        /// </summary>
        [Fact]
        public void TextOffsetTest()
        {
            // TODO unit test for the property 'TextOffset'
        }
    }
}
