/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing CompletionsCreateRequestPrompt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompletionsCreateRequestPromptTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompletionsCreateRequestPrompt
        //private CompletionsCreateRequestPrompt instance;

        public CompletionsCreateRequestPromptTests()
        {
            // TODO uncomment below to create an instance of CompletionsCreateRequestPrompt
            //instance = new CompletionsCreateRequestPrompt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompletionsCreateRequestPrompt
        /// </summary>
        [Fact]
        public void CompletionsCreateRequestPromptInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompletionsCreateRequestPrompt
            //Assert.IsType<CompletionsCreateRequestPrompt>(instance);
        }
    }
}
