/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing ContentFilterResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentFilterResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentFilterResult
        //private ContentFilterResult instance;

        public ContentFilterResultTests()
        {
            // TODO uncomment below to create an instance of ContentFilterResult
            //instance = new ContentFilterResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentFilterResult
        /// </summary>
        [Fact]
        public void ContentFilterResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentFilterResult
            //Assert.IsType<ContentFilterResult>(instance);
        }

        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Fact]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }

        /// <summary>
        /// Test the property 'Filtered'
        /// </summary>
        [Fact]
        public void FilteredTest()
        {
            // TODO unit test for the property 'Filtered'
        }
    }
}
