/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing ContentFilterResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentFilterResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentFilterResults
        //private ContentFilterResults instance;

        public ContentFilterResultsTests()
        {
            // TODO uncomment below to create an instance of ContentFilterResults
            //instance = new ContentFilterResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentFilterResults
        /// </summary>
        [Fact]
        public void ContentFilterResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentFilterResults
            //Assert.IsType<ContentFilterResults>(instance);
        }

        /// <summary>
        /// Test the property 'Sexual'
        /// </summary>
        [Fact]
        public void SexualTest()
        {
            // TODO unit test for the property 'Sexual'
        }

        /// <summary>
        /// Test the property 'Violence'
        /// </summary>
        [Fact]
        public void ViolenceTest()
        {
            // TODO unit test for the property 'Violence'
        }

        /// <summary>
        /// Test the property 'Hate'
        /// </summary>
        [Fact]
        public void HateTest()
        {
            // TODO unit test for the property 'Hate'
        }

        /// <summary>
        /// Test the property 'SelfHarm'
        /// </summary>
        [Fact]
        public void SelfHarmTest()
        {
            // TODO unit test for the property 'SelfHarm'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
