/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing CreateChatCompletionRequestAllOfFunctionCall
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateChatCompletionRequestAllOfFunctionCallTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateChatCompletionRequestAllOfFunctionCall
        //private CreateChatCompletionRequestAllOfFunctionCall instance;

        public CreateChatCompletionRequestAllOfFunctionCallTests()
        {
            // TODO uncomment below to create an instance of CreateChatCompletionRequestAllOfFunctionCall
            //instance = new CreateChatCompletionRequestAllOfFunctionCall();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateChatCompletionRequestAllOfFunctionCall
        /// </summary>
        [Fact]
        public void CreateChatCompletionRequestAllOfFunctionCallInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateChatCompletionRequestAllOfFunctionCall
            //Assert.IsType<CreateChatCompletionRequestAllOfFunctionCall>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
