/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing EmbeddingsCreate200ResponseDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmbeddingsCreate200ResponseDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmbeddingsCreate200ResponseDataInner
        //private EmbeddingsCreate200ResponseDataInner instance;

        public EmbeddingsCreate200ResponseDataInnerTests()
        {
            // TODO uncomment below to create an instance of EmbeddingsCreate200ResponseDataInner
            //instance = new EmbeddingsCreate200ResponseDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmbeddingsCreate200ResponseDataInner
        /// </summary>
        [Fact]
        public void EmbeddingsCreate200ResponseDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmbeddingsCreate200ResponseDataInner
            //Assert.IsType<EmbeddingsCreate200ResponseDataInner>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'VarObject'
        /// </summary>
        [Fact]
        public void VarObjectTest()
        {
            // TODO unit test for the property 'VarObject'
        }

        /// <summary>
        /// Test the property 'Embedding'
        /// </summary>
        [Fact]
        public void EmbeddingTest()
        {
            // TODO unit test for the property 'Embedding'
        }
    }
}
