/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing EmbeddingsCreate200ResponseUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmbeddingsCreate200ResponseUsageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmbeddingsCreate200ResponseUsage
        //private EmbeddingsCreate200ResponseUsage instance;

        public EmbeddingsCreate200ResponseUsageTests()
        {
            // TODO uncomment below to create an instance of EmbeddingsCreate200ResponseUsage
            //instance = new EmbeddingsCreate200ResponseUsage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmbeddingsCreate200ResponseUsage
        /// </summary>
        [Fact]
        public void EmbeddingsCreate200ResponseUsageInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmbeddingsCreate200ResponseUsage
            //Assert.IsType<EmbeddingsCreate200ResponseUsage>(instance);
        }

        /// <summary>
        /// Test the property 'PromptTokens'
        /// </summary>
        [Fact]
        public void PromptTokensTest()
        {
            // TODO unit test for the property 'PromptTokens'
        }

        /// <summary>
        /// Test the property 'TotalTokens'
        /// </summary>
        [Fact]
        public void TotalTokensTest()
        {
            // TODO unit test for the property 'TotalTokens'
        }
    }
}
