/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing EmbeddingsCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmbeddingsCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmbeddingsCreateRequest
        //private EmbeddingsCreateRequest instance;

        public EmbeddingsCreateRequestTests()
        {
            // TODO uncomment below to create an instance of EmbeddingsCreateRequest
            //instance = new EmbeddingsCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmbeddingsCreateRequest
        /// </summary>
        [Fact]
        public void EmbeddingsCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmbeddingsCreateRequest
            //Assert.IsType<EmbeddingsCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Fact]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'InputType'
        /// </summary>
        [Fact]
        public void InputTypeTest()
        {
            // TODO unit test for the property 'InputType'
        }
    }
}
