/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing ExtensionsChatCompletionChoice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtensionsChatCompletionChoiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtensionsChatCompletionChoice
        //private ExtensionsChatCompletionChoice instance;

        public ExtensionsChatCompletionChoiceTests()
        {
            // TODO uncomment below to create an instance of ExtensionsChatCompletionChoice
            //instance = new ExtensionsChatCompletionChoice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtensionsChatCompletionChoice
        /// </summary>
        [Fact]
        public void ExtensionsChatCompletionChoiceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtensionsChatCompletionChoice
            //Assert.IsType<ExtensionsChatCompletionChoice>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'FinishReason'
        /// </summary>
        [Fact]
        public void FinishReasonTest()
        {
            // TODO unit test for the property 'FinishReason'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
