/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing ExtensionsChatCompletionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtensionsChatCompletionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtensionsChatCompletionsRequest
        //private ExtensionsChatCompletionsRequest instance;

        public ExtensionsChatCompletionsRequestTests()
        {
            // TODO uncomment below to create an instance of ExtensionsChatCompletionsRequest
            //instance = new ExtensionsChatCompletionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtensionsChatCompletionsRequest
        /// </summary>
        [Fact]
        public void ExtensionsChatCompletionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtensionsChatCompletionsRequest
            //Assert.IsType<ExtensionsChatCompletionsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'TopP'
        /// </summary>
        [Fact]
        public void TopPTest()
        {
            // TODO unit test for the property 'TopP'
        }

        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Fact]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }

        /// <summary>
        /// Test the property 'Stop'
        /// </summary>
        [Fact]
        public void StopTest()
        {
            // TODO unit test for the property 'Stop'
        }

        /// <summary>
        /// Test the property 'MaxTokens'
        /// </summary>
        [Fact]
        public void MaxTokensTest()
        {
            // TODO unit test for the property 'MaxTokens'
        }

        /// <summary>
        /// Test the property 'PresencePenalty'
        /// </summary>
        [Fact]
        public void PresencePenaltyTest()
        {
            // TODO unit test for the property 'PresencePenalty'
        }

        /// <summary>
        /// Test the property 'FrequencyPenalty'
        /// </summary>
        [Fact]
        public void FrequencyPenaltyTest()
        {
            // TODO unit test for the property 'FrequencyPenalty'
        }

        /// <summary>
        /// Test the property 'LogitBias'
        /// </summary>
        [Fact]
        public void LogitBiasTest()
        {
            // TODO unit test for the property 'LogitBias'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'DataSources'
        /// </summary>
        [Fact]
        public void DataSourcesTest()
        {
            // TODO unit test for the property 'DataSources'
        }
    }
}
