/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing InnerError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InnerErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InnerError
        //private InnerError instance;

        public InnerErrorTests()
        {
            // TODO uncomment below to create an instance of InnerError
            //instance = new InnerError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InnerError
        /// </summary>
        [Fact]
        public void InnerErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" InnerError
            //Assert.IsType<InnerError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'ContentFilterResults'
        /// </summary>
        [Fact]
        public void ContentFilterResultsTest()
        {
            // TODO unit test for the property 'ContentFilterResults'
        }
    }
}
