/*
 * Azure OpenAI Service API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2023-09-01-preview
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureOpenAI.Model;
using AzureOpenAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureOpenAI.Test.Model
{
    /// <summary>
    ///  Class for testing TranscriptionsCreate200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranscriptionsCreate200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TranscriptionsCreate200Response
        //private TranscriptionsCreate200Response instance;

        public TranscriptionsCreate200ResponseTests()
        {
            // TODO uncomment below to create an instance of TranscriptionsCreate200Response
            //instance = new TranscriptionsCreate200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TranscriptionsCreate200Response
        /// </summary>
        [Fact]
        public void TranscriptionsCreate200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TranscriptionsCreate200Response
            //Assert.IsType<TranscriptionsCreate200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Fact]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }
    }
}
